---
title: "You Draw It: Eye Fitting Straight Lines in the Modern Era"  
subtitle: "Pilot Data (Twitter / Reddit / Direct Email)"
author: "Emily Robinson"
date: "May 21, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	options(knitr.kable.NA = ''), 
	fig.height = 12, 
	fig.width = 12,
	fig.align = 'center'
)
library(RSQLite)
library(DBI)
library(tidyverse)
library(lme4)
library(lmerTest)
library(emmeans)
```

## Data

```{r obtain-data}
# Connect to database
filename <- "../you_draw_it_data.db"
sqlite.driver <- dbDriver("SQLite")
db_con <- dbConnect(sqlite.driver, dbname = filename)
# dbListTables(db_con)

# Import eyefitting parameter details
eyefitting_parameter_details <- dbReadTable(db_con,"eyefitting_parameter_details") %>%
  mutate(parm_id = as.factor(as.character(parm_id)))

# Import user data
users <- dbReadTable(db_con,"users") %>%
  filter(study_starttime > 1620152231) %>%
  select(-ip_address) %>%
  mutate(participantID = as.factor(as.character(as.numeric(as.factor(paste(nick_name, "_", study_starttime, sep = ""))))))

# Import exponential prediction feedback data
eyefitting_feedback <- dbReadTable(db_con,"feedback") %>%
  filter(study_starttime > 1620152231) %>%
  filter(parm_id %in% c("S", "F", "V", "N")) %>%
  left_join(eyefitting_parameter_details, by = "parm_id") %>%
  mutate(residual.drawn = ydrawn - y) %>%
  left_join(users, by = c("nick_name", "study_starttime")) %>%
  filter(recruitment != "I am the researcher") %>%
  mutate(plotID = as.factor(as.character(as.numeric(as.factor(paste(nick_name, "_", start_time, "_", end_time, sep = ""))))),
         parm_id = as.factor(as.character(parm_id)))

# Import exponential prediction simulated data
eyefitting_simulated_data <- dbReadTable(db_con,"simulated_data") %>%
  filter(study_starttime > 1620152231) %>%
  filter(parm_id %in% c("S", "F", "V", "N")) %>%
  left_join(eyefitting_parameter_details, by = "parm_id") %>%
  left_join(users, by = c("nick_name", "study_starttime")) %>%
  filter(recruitment != "I am the researcher") %>%
  mutate(parm_id = as.factor(as.character(parm_id)))

# Disconnect from database
dbDisconnect(db_con)
```

### Feedback Data Summary

```{r feedback-summary}
eyefitting_feedback %>%
  select(parm_id, participantID, plotID) %>%
  unique() %>%
  group_by(parm_id, participantID) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  group_by(participantID) %>%
  mutate(total = sum(count)) %>%
  ungroup() %>%
  pivot_wider(id_cols = c("participantID", "total"),
              names_from = "parm_id",
              values_from = "count") %>%
  arrange(as.numeric(as.character(participantID))) %>%
  knitr::kable()
```

### Simulated Data Summary

```{r simulated-summary}
eyefitting_simulated_data %>%
  filter(dataset == "line_data", x == 10.00) %>%
  group_by(parm_id, participantID) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  group_by(participantID) %>%
  mutate(total = sum(count)) %>%
  ungroup() %>%
  pivot_wider(id_cols = c("participantID", "total"),
              names_from = "parm_id",
              values_from = "count") %>%
  arrange(as.numeric(as.character(participantID))) %>%
  knitr::kable()
```

## Users

```{r users}
users %>% select(participantID, age, gender, academic_study, recruitment) %>% knitr::kable()
```


```{r loess-smoother, echo = F}

# Fit Loess Smoother
loess.models <- eyefitting_feedback %>%
        tidyr::nest(-plotID) %>%
        dplyr::mutate(
                # Perform loess calculation on each plotID
                loess.fit = purrr::map(data, loess,
                               formula = ydrawn ~ x),
                # Retrieve the fitted values from each model
                yloess = purrr::map(loess.fit, `[[`, "fitted")
        )

# Apply fitted y's as a new column
eyefitting_feedback.smooth <- loess.models %>%
        dplyr::select(-loess.fit) %>%
        tidyr::unnest(cols = c(data, yloess)) %>%
  mutate(residual.loess = yloess - y) %>%
  select(participantID, age, gender, academic_study, recruitment, plotID, parm_id, x, y, ydrawn, yloess, residual.drawn, residual.loess, nick_name, study_starttime, start_time, end_time)

factorCols <- c("plotID", "parm_id", "nick_name", "study_starttime", "age", "gender", "academic_study", "recruitment", "participantID")
eyefitting_feedback.smooth[,factorCols] <- lapply(eyefitting_feedback.smooth[,factorCols], factor)

# summary(eyefitting_feedback.smooth)
```


```{r pca-calculation, echo = T, include = F}
require(pls)
# Fit First PCA
pca.models <- eyefitting_simulated_data %>%
        filter(dataset == "point_data") %>%
        mutate(dataID = as.factor(paste(participantID, parm_id, sep = ""))) %>%
        tidyr::nest(-dataID) %>%
        dplyr::mutate(
                # Perform pc1 calculation on each plotID
                pc.fit = purrr::map(data, loess,
                               formula = y ~ x),
                # Retrieve the fitted values from each model
                yPC1 = purrr::map(pc.fit, `[[`, "fitted")
        )

# Apply fitted y's as a new column
eyefitting_simulated_data.pca <- pca.models %>%
        dplyr::select(-pc.fit) %>%
        tidyr::unnest(cols = c(data, yPC1)) %>%
  select(participantID, age, gender, academic_study, recruitment, parm_id, x, y, yPC1, nick_name, study_starttime)

factorCols <- c("parm_id", "nick_name", "study_starttime", "age", "gender", "academic_study", "recruitment", "participantID")
eyefitting_simulated_data.pca[,factorCols] <- lapply(eyefitting_simulated_data.pca[,factorCols], factor)

summary(eyefitting_simulated_data.pca)
```

## Spaghetti Plots

### Simulated Data

```{r spaghetti-simulated}
eyefitting_simulated_data %>%
  filter(dataset == "line_data") %>%
  arrange(participantID, x) %>%
  ggplot(aes(x = x, y = y, group = participantID)) +
  geom_line(alpha = 0.3) +
  facet_wrap(~parm_id, ncol = 2) +
  theme_bw() +
  theme(aspect.ratio = 1)
```

### All Overlaid (No Smoother)

```{r spaghetti-all-overlaid-no-smoother}
eyefitting_simulated_data %>%
  filter(dataset == "line_data") %>%
  arrange(participantID, x) %>%
  ggplot(aes(x = x)) +
  geom_line(data = eyefitting_feedback.smooth, aes(y = ydrawn, group = plotID), color = "steelblue", alpha = 0.5) +
  geom_line(alpha = 0.5, aes(y = y, group = participantID)) +
  facet_wrap(~parm_id, ncol = 2) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_x_continuous(limits = c(0, 20))
```

### All Overlaid (Loess Smoother)

```{r spaghetti-all-overlaid-loess-smoother}
eyefitting_simulated_data %>%
  filter(dataset == "line_data") %>%
  arrange(participantID, x) %>%
  ggplot(aes(x = x)) +
  geom_line(alpha = 0.3, aes(y = y, group = participantID)) +
  geom_line(data = eyefitting_feedback.smooth, aes(y = yloess, group = plotID), color = "steelblue", alpha = 0.3) +
  facet_wrap(~parm_id, ncol = 2) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_x_continuous(limits = c(0, 20))
```

<hr>
### Residuals (No Smoother)

```{r residuals-no-smoother}
eyefitting.spaghetti.plot.raw <- eyefitting_feedback.smooth %>%
  arrange(participantID, parm_id, x) %>%
  ggplot(aes(x = x, y = residual.drawn, group = plotID)) +
  geom_line(alpha = 0.7, color = "steelblue") +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", alpha = 0.5) +
  facet_wrap(~parm_id, ncol = 2) +
  theme_bw() +
  theme(aspect.ratio = 1)
eyefitting.spaghetti.plot.raw 
```

### Residual (Loess Smoother)

```{r residuals-loess-smoother}
eyefitting.spaghetti.plot.smooth <- eyefitting_feedback.smooth %>%
  arrange(participantID, parm_id, x) %>%
  ggplot(aes(x = x, y = residual.loess, group = plotID)) +
  geom_line(alpha = 0.7, color = "steelblue") +
  geom_hline(yintercept = 0, color = "black", linetype = "dashed", alpha = 0.5) +
  facet_wrap(~parm_id, ncol = 2) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_color_manual("Scale", values = c("steelblue", "orange"))
eyefitting.spaghetti.plot.smooth
```
