---
title: "Prediction (You Draw It)"
author: "Emily Robinson"
date: "Spring 2022"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: true
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	cache = TRUE,
	fig.align = 'center'
)
library(tidyverse)
`%notin%` <- Negate(`%in%`)

library(RSQLite)
library(DBI)
library(here)
library(readr)
library(digest)

library(openssl)
library(mgcv)
library(lme4)
library(tictoc)

source("gamm-predict-function.R")
```

# Data

```{r eval = F}
# user data
db_con <- dbConnect(dbDriver("SQLite"), dbname = here("perception-of-statistical-graphics/databases/00_demographics_db.db"))
users <- dbReadTable(db_con,"users")
completed_sections <- dbReadTable(db_con,"completed_sections")
dbDisconnect(db_con)

# you draw it data
db_con <- dbConnect(dbDriver("SQLite"), dbname = here("perception-of-statistical-graphics/databases/02_you_draw_it_db.db"))
youdrawit_feedback <- dbReadTable(db_con,"feedback") %>%
  filter(parm_id %notin% c("F", "S", "N", "V"))
youdrawit_simulated <- dbReadTable(db_con, "simulated_data")
dbDisconnect(db_con)

# combine you draw it feedback, user data
joinCols <- c("nick_name", "ip_address", "study_starttime", "prolific_id")
youdrawit_data_orig <- right_join(users, youdrawit_feedback, by = joinCols)  %>%
  # filter(recruitment != "I am the researcher") %>%
  filter(parm_id %notin% c("F", "S", "N", "V")) %>%
  rename(ynls = y) %>%
  separate(parm_id, into = c("beta", "points_truncated", "scale"), sep = "-") %>%
  select(-linear) %>%
  mutate(scale = ifelse(scale == "false", "log", "linear")) %>%
  rowwise() %>%
  mutate(participant_id = digest(paste(nick_name, ip_address, study_starttime, prolific_id, sep = "-"), "md5"), .after = prolific_id) %>%
  mutate(plot_id = digest(paste(nick_name, ip_address, study_starttime, prolific_id, start_time, end_time, beta, points_truncated, scale, sep = "-"), "md5"), .after = prolific_id)

factorCols <- c("nick_name", "ip_address", "prolific_id", "age", "gender", "academic_study", "computer_mouse", "recruitment", "participant_id", "plot_id", "beta", "points_truncated", "scale")
youdrawit_data_orig[,factorCols] <- lapply(youdrawit_data_orig[,factorCols], factor)


# fit loess smoother
loess_models <- youdrawit_data_orig %>%
  as_tibble() %>%
  # tidyr::nest(-plot_id) %>%
  tidyr::nest(data = c(nick_name, ip_address, study_starttime, prolific_id, participant_id, 
    age, gender, academic_study, computer_mouse, recruitment, 
    beta, points_truncated, scale, x, ynls, ydrawn, start_time, 
    end_time)) %>%
  dplyr::mutate(loess_fit = purrr::map(data, loess, formula = ydrawn ~ x),
                yloess = purrr::map(loess_fit, `[[`, "fitted"))

# apply fitted y's as a new column
youdrawit_model_data <- loess_models %>%
        dplyr::select(-loess_fit) %>%
        tidyr::unnest(cols = c(data, yloess)) %>%
  mutate(residual_nls_drawn = ydrawn - ynls,
         residual_nls_loess = yloess - ynls) %>%
  select(nick_name, ip_address, study_starttime, prolific_id, age, gender, academic_study, computer_mouse, recruitment, participant_id, plot_id, beta, points_truncated, scale, start_time, end_time, x, ynls, ydrawn, yloess, residual_nls_drawn, residual_nls_loess)

# simulated data
youdrawit_simulated_data <- right_join(users, youdrawit_simulated, by = joinCols)  %>%
  # filter(recruitment != "I am the researcher") %>%
  filter(parm_id %notin% c("F", "S", "N", "V")) %>%
  separate(parm_id, into = c("beta", "points_truncated", "scale"), sep = "-") %>%
  mutate(scale = ifelse(scale == "false", "log", "linear")) %>%
  rowwise() %>%
  mutate(data_id =  as.factor(digest(paste(nick_name, ip_address, study_starttime, prolific_id, beta, points_truncated, scale, sep = "-"), "md5")), .before = beta) %>%
  mutate(participant_id = as.factor(digest(paste(nick_name, ip_address, study_starttime, prolific_id, sep = "-"), "md5")), .before = data_id)

factorCols <- c("nick_name", "ip_address", "prolific_id", "age", "gender", "academic_study", "computer_mouse", "recruitment", "participant_id", "beta", "points_truncated", "scale", "data_id", "dataset")
youdrawit_simulated_data[,factorCols] <- lapply(youdrawit_simulated_data[,factorCols], factor)

write.csv(youdrawit_model_data, file = here("analyses/02a-you-draw-it/data/youdrawit-model-data.csv"), row.names = F, na = "")
write.csv(youdrawit_simulated_data, file = here("analyses/02a-you-draw-it/data/youdrawit-simulated-data.csv"), row.names = F, na = "")

```


```{r}
# read in youdrawit_model_data and eyefitting_simulated_data
youdrawit_model_data     <- read.csv(here("analyses/02a-you-draw-it/data/youdrawit-model-data.csv"))

factorCols <- c("nick_name", "ip_address", "prolific_id", "age", "gender", "academic_study", "computer_mouse", "recruitment", "participant_id", "plot_id", "beta", "points_truncated", "scale")
youdrawit_model_data[,factorCols] <- lapply(youdrawit_model_data[,factorCols], factor)

youdrawit_simulated_data <- read.csv(here("analyses/02a-you-draw-it/data/youdrawit-simulated-data.csv"))

youdrawit_model_data %>%
  select(participant_id, beta, points_truncated, scale, x, ynls, ydrawn, yloess, residual_nls_drawn) %>%
  head() %>%
  knitr::kable()
```

There are `r length(unique(youdrawit_model_data$participant_id)) %>% as.numeric` participants and `r length(unique(youdrawit_model_data$plot_id)) %>% as.numeric()` 'You Draw It' task plots complete.

# Check Data
```{r}
youdrawit_model_data %>%
  filter(x == 20) %>%
  mutate(treatment = paste(beta, points_truncated, scale, sep = "-")) %>%
  group_by(participant_id) %>%
  mutate(n = n()) %>%
  group_by(participant_id, n, treatment) %>%
  summarize(count = n()) %>%
  pivot_wider(id_cols = c("participant_id", "n"),
              names_from = "treatment",
              values_from = "count")
```

# Raw Plots

```{r, fig.width = 12, fig.height = 60, eval = F, include = F}
youdrawit_model_data %>%
  ggplot(aes(x = x)) +
  geom_line(aes(y = ynls, group = interaction(plot_id, scale)), color = "black") +
  geom_line(aes(y = ydrawn, group = interaction(plot_id, scale), color = scale)) +
  geom_point(data = youdrawit_simulated_data %>% filter(dataset == "point_data"), aes(y = y), size = 0.8, color = "gray30", shape = 1) +
  facet_grid(participant_id ~ beta + points_truncated) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_color_manual(values = c("steelblue", "darkorange"))
```

```{r}
spaghetti_plot <- youdrawit_model_data %>%
  # filter(beta == "beta0.1") %>%
  ggplot(aes(x = x)) +
  geom_line(aes(y = yloess, group = plot_id, color = scale), alpha = 0.2) +
  geom_line(alpha = 0.01, aes(y = ynls, group = plot_id, color = "Fitted NLS")) +
  facet_grid(beta ~ points_truncated, scales = "free") +
  theme_bw() +
  theme(aspect.ratio = 1,
        legend.position = "bottom"
        ) +
  scale_color_manual("", values = c("black", "steelblue", "orange"), labels = c("Fitted \n (NLS)", "Linear Scale \n (drawn, loess)", "Log Scale \n (drawn, loess)")) +
  scale_x_continuous(limits = c(10, 20)) +
  scale_y_continuous("y") +
  guides(color = guide_legend(override.aes = list(alpha = 1)),
         fill = guide_legend(override.aes = list(alpha = 1)))
spaghetti_plot
```

# Residual Plots

```{r}
youdrawit_model_data %>%
  ggplot(aes(x = x, y = residual_nls_drawn)) +
  geom_line(aes(group = interaction(plot_id, scale), color = scale), alpha = 0.05) +
  geom_hline(aes(yintercept = 0), color = 'black', linetype = 'dashed') +
  facet_grid(beta ~ points_truncated, scales = "free_y") +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_color_manual(values = c("steelblue", "darkorange")) +
  ggtitle("Drawn Residuals")

youdrawit_model_data %>%
  ggplot(aes(x = x, y = residual_nls_loess)) +
  geom_line(aes(group = interaction(plot_id, scale), color = scale), alpha = 0.05) +
  geom_hline(aes(yintercept = 0), color = 'black', linetype = 'dashed') +
  facet_grid(beta ~ points_truncated, scales = "free_y") +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_color_manual(values = c("steelblue", "darkorange")) +
  ggtitle("Loess Residuals")
```

# Smoothing Splines (GAMM)

## Both Betas

```{r, eval = F, echo = F}
tic()
exp.gamm.reduced <- bam(residual_nls_drawn ~ -1 + beta:points_truncated:scale + 
                        s(x, by = beta:points_truncated:scale) +
                        s(participant_id, bs = "re") +
                        s(x,participant_id, bs = "re"),
                        method = "REML",
                        data = youdrawit_model_data)
plot(exp.gamm.reduced, pages = 2,all.terms=TRUE)
toc()

# summary(exp.gamm.reduced)
anova(exp.gamm.reduced)

# Obtain Predictions
grid_data.exp.reduced <- expand_grid(beta = c("beta0.1", "beta0.23"),
                         points_truncated = c("10", "15"),
                         scale = c("linear", "log"),
                         x = seq(10,20, 0.5),
                         participant_id = youdrawit_model_data$participant_id[1])
preds.exp.reduced <- predict_gamm(exp.gamm.reduced, newdata = grid_data.exp.reduced, se = T, re_form = NA)
grid_data.exp.reduced$estimate <- preds.exp.reduced$prediction
grid_data.exp.reduced$lower <- preds.exp.reduced$prediction - (1.96 * preds.exp.reduced$se)
grid_data.exp.reduced$upper <- preds.exp.reduced$prediction + (1.96 * preds.exp.reduced$se)
# head(grid_data.exp.reduced)
write.csv(grid_data.exp.reduced, file = "data/youdrawit-exponential-prediction-gamm-preds.csv", row.names = F, na = "")
```

```{r, eval = T, echo = F}
# Plot Predictions
grid_data.exp.reduced <- read.csv(file = "data/youdrawit-exponential-prediction-gamm-preds.csv")

# Plot predictions with individual lines
grid_data.exp.reduced %>%
  mutate(beta = substr(beta, 5,10)) %>%
  ggplot(aes(x = x, y = estimate, group = scale, color = scale, fill = scale)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), color = NA, alpha = 0.7) +
  geom_line() +
  geom_line(data = youdrawit_model_data %>%
  mutate(beta = substr(beta, 5,10)), aes(x = x, y = residual_nls_drawn, group = interaction(plot_id, scale)), alpha = 0.05) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  facet_grid(beta ~ points_truncated, scales = "free", labeller = labeller(beta = label_both, points_truncated = label_both)) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_y_continuous("Residual \n (yloess - y)") +
  scale_color_manual("Scale", values = c("steelblue", "orange")) +
  scale_fill_manual("Scale", values = c("steelblue", "orange"))

# Plot Predictions
grid_data.exp.reduced %>%
  mutate(beta = substr(beta, 5,10)) %>%
  ggplot(aes(x = x, y = estimate, group = scale, color = scale, fill = scale)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), color = NA, alpha = 0.3) +
  geom_line() +
  # geom_line(data = youdrawit_model_data, aes(x = x, y = residual_nls_drawn, group = interaction(plot_id, scale)), alpha = 0.05) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  facet_grid(beta ~ points_truncated, scales = "free", labeller = labeller(beta = label_both, points_truncated = label_both)) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_y_continuous("Residual \n (yloess - y)") +
  scale_color_manual("Scale", values = c("steelblue", "orange")) +
  scale_fill_manual("Scale", values = c("steelblue", "orange"))
```

## Beta 0.1

```{r, eval = F, echo = F}
tic()
exp.gamm.reduced_0.1 <- bam(residual_nls_drawn ~ -1 + points_truncated:scale + 
                        s(x, by = points_truncated:scale) +
                        s(participant_id, bs = "re") +
                        s(x,participant_id, bs = "re"),
                        method = "REML",
                        data = youdrawit_model_data %>% filter(beta == "beta0.1"))
# plot(exp.gamm.reduced_0.1, pages = 2,all.terms=TRUE)
toc()

# summary(exp.gamm.reduced_0.1)
anova(exp.gamm.reduced_0.1)

# Obtain Predictions
grid_data.exp.reduced_0.1 <- expand_grid(beta = c("beta0.1"),
                         points_truncated = c("10", "15"),
                         scale = c("linear", "log"),
                         x = seq(10,20, 0.5),
                         participant_id = youdrawit_model_data$participant_id[1])
preds.exp.reduced_0.1 <- predict_gamm(exp.gamm.reduced_0.1, newdata = grid_data.exp.reduced_0.1, se = T, re_form = NA)
grid_data.exp.reduced_0.1$estimate <- preds.exp.reduced_0.1$prediction
grid_data.exp.reduced_0.1$lower <- preds.exp.reduced_0.1$prediction - (1.96 * preds.exp.reduced_0.1$se)
grid_data.exp.reduced_0.1$upper <- preds.exp.reduced_0.1$prediction + (1.96 * preds.exp.reduced_0.1$se)
# head(grid_data.exp.reduced_0.1)
write.csv(grid_data.exp.reduced_0.1, file = "data/youdrawit-exponential-prediction-gamm-preds-0.1.csv", row.names = F, na = "")
```

```{r, eval = T, echo = F}
# Plot Predictions
grid_data.exp.reduced_0.1 <- read.csv(file = "data/youdrawit-exponential-prediction-gamm-preds-0.1.csv")

# Plot predictions with individual lines
grid_data.exp.reduced_0.1 %>%
  mutate(beta = substr(beta, 5,10)) %>%
  ggplot(aes(x = x, y = estimate, group = scale, color = scale, fill = scale)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), color = NA, alpha = 0.7) +
  geom_line() +
  geom_line(data = youdrawit_model_data %>% filter(beta == "beta0.1") %>% mutate(beta = substr(beta, 5,10)), 
            aes(x = x, y = residual_nls_drawn, group = interaction(plot_id, scale)), alpha = 0.05) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  facet_grid(beta ~ points_truncated, scales = "free", labeller = labeller(beta = label_both, points_truncated = label_both)) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_y_continuous("Residual \n (yloess - y)") +
  scale_color_manual("Scale", values = c("steelblue", "orange")) +
  scale_fill_manual("Scale", values = c("steelblue", "orange"))

# Plot Predictions
grid_data.exp.reduced_0.1 %>%
  mutate(beta = substr(beta, 5,10)) %>%
  ggplot(aes(x = x, y = estimate, group = scale, color = scale, fill = scale)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), color = NA, alpha = 0.3) +
  geom_line() +
  # geom_line(data = youdrawit_model_data, aes(x = x, y = residual_nls_drawn, group = interaction(plot_id, scale)), alpha = 0.05) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  facet_grid(beta ~ points_truncated, scales = "free", labeller = labeller(beta = label_both, points_truncated = label_both)) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_y_continuous("Residual \n (yloess - y)") +
  scale_color_manual("Scale", values = c("steelblue", "orange")) +
  scale_fill_manual("Scale", values = c("steelblue", "orange"))
```

## Beta 0.23

```{r, eval = F, echo = F}
tic()
exp.gamm.reduced_0.23 <- bam(residual_nls_drawn ~ -1 + points_truncated:scale + 
                        s(x, by = points_truncated:scale) +
                        s(participant_id, bs = "re") +
                        s(x,participant_id, bs = "re"),
                        method = "REML",
                        data = youdrawit_model_data %>% filter(beta == "beta0.23"))
# plot(exp.gamm.reduced, pages = 2,all.terms=TRUE)
toc()

# summary(exp.gamm.reduced)
anova(exp.gamm.reduced_0.23)

# Obtain Predictions
grid_data.exp.reduced_0.23 <- expand_grid(beta = c("beta0.23"),
                         points_truncated = c("10", "15"),
                         scale = c("linear", "log"),
                         x = seq(10,20, 0.5),
                         participant_id = youdrawit_model_data$participant_id[1])
preds.exp.reduced_0.23 <- predict_gamm(exp.gamm.reduced_0.23, newdata = grid_data.exp.reduced_0.23, se = T, re_form = NA)
grid_data.exp.reduced_0.23$estimate <- preds.exp.reduced_0.23$prediction
grid_data.exp.reduced_0.23$lower <- preds.exp.reduced_0.23$prediction - (1.96 * preds.exp.reduced_0.23$se)
grid_data.exp.reduced_0.23$upper <- preds.exp.reduced_0.23$prediction + (1.96 * preds.exp.reduced_0.23$se)
# head(grid_data.exp.reduced_0.23)
write.csv(grid_data.exp.reduced_0.23, file = "data/youdrawit-exponential-prediction-gamm-preds-0.23.csv", row.names = F, na = "")
```

```{r, eval = T, echo = F}
# Plot Predictions
grid_data.exp.reduced_0.23 <- read.csv(file = "data/youdrawit-exponential-prediction-gamm-preds-0.23.csv")

# Plot predictions with individual lines
grid_data.exp.reduced_0.23 %>%
  mutate(beta = substr(beta, 5,10)) %>%
  ggplot(aes(x = x, y = estimate, group = scale, color = scale, fill = scale)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), color = NA, alpha = 0.7) +
  geom_line() +
  geom_line(data = youdrawit_model_data %>% filter(beta == "beta0.23") %>% mutate(beta = substr(beta, 5,10)), 
            aes(x = x, y = residual_nls_drawn, group = interaction(plot_id, scale)), alpha = 0.05) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  facet_grid(beta ~ points_truncated, scales = "free", labeller = labeller(beta = label_both, points_truncated = label_both)) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_y_continuous("Residual \n (yloess - y)") +
  scale_color_manual("Scale", values = c("steelblue", "orange")) +
  scale_fill_manual("Scale", values = c("steelblue", "orange"))

# Plot Predictions
grid_data.exp.reduced_0.23 %>%
  mutate(beta = substr(beta, 5,10)) %>%
  ggplot(aes(x = x, y = estimate, group = scale, color = scale, fill = scale)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), color = NA, alpha = 0.3) +
  geom_line() +
  # geom_line(data = youdrawit_model_data, aes(x = x, y = residual_nls_drawn, group = interaction(plot_id, scale)), alpha = 0.05) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  facet_grid(beta ~ points_truncated, scales = "free", labeller = labeller(beta = label_both, points_truncated = label_both)) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_y_continuous("Residual \n (yloess - y)") +
  scale_color_manual("Scale", values = c("steelblue", "orange")) +
  scale_fill_manual("Scale", values = c("steelblue", "orange"))
```



