---
title: "Simulated Data Verification"
author: "Emily Robinson"
date: "Spring 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	fig.align = 'center'
)
library(tidyverse)
library(scales)
library(patchwork)
library(gganimate)
```

## Exponential Prediction

### Data Generation Function
```{r expDataGen-function}
expDataGen <-
  function(beta,
           sd,
           N = 30,
           x_min = 0,
           x_max = 20,
           x_by  = 0.25){

    # Set up x values
    xVals <- seq(0, x_max, length.out = floor(N*1))
    xVals <- sample(xVals, N, replace = FALSE)
    xVals <- jitter(xVals)
    xVals <- ifelse(xVals < x_min, x_min, xVals) 
    xVals <- ifelse(xVals > x_max, x_max, xVals)

    # Generate "good" errors
    repeat{
      errorVals <- rnorm(length(xVals), 0, sd)
      if(mean(errorVals[floor(N/3)]) < 2*sd & mean(errorVals[floor(N/3)] > -2*sd)){
        break
      }
    }

    # Simulate point data
    point_data <- tibble(x = xVals,
                         y = exp(x*beta + errorVals),
                         dataset = "point_data") %>%
      arrange(x)

    # Obtain starting value for beta
    lm.fit <- lm(log(y) ~ x, data = point_data)
    beta.0 <- coef(lm.fit)[1] %>% as.numeric()
    # Use NLS to fit a better line to the data
    start <- list(beta = beta.0)
    nonlinear.fit <- nls(y ~ exp(x*beta),
                         data = point_data,
                         start = start)
    betahat <- coef(nonlinear.fit)[1] %>% as.numeric()

    # Simulate best fit line data
    line_data <- tibble(x = seq(x_min, x_max, x_by),
                        y = exp(x*betahat),
                        dataset = "line_data")

    data <- list(point_data = point_data, line_data = line_data)

    return(data)
  }
```

### Parameter Details
```{r expParms, echo = F}
exp_parameter_details <- data.frame(parm_id = c("exp_low", "exp_high"),
                                     beta = c(0.1, 0.23), 
                                     sd = c(0.09, 0.25)) %>%
                          expand_grid(N = 30,
                                      x_min = 0,
                                      x_max = 20,
                                      x_by = 0.25
                          )
exp_parameter_details %>% knitr::kable()
```

### Simulate Data
```{r expSim}
exp_data <- exp_parameter_details %>%
  expand_grid(B = c(1:100)) %>%
  mutate(data = purrr::pmap(list(beta  = beta,
                                 sd    = sd,
                                 N     = N,
                                 x_min = x_min,
                                 x_max = x_max,
                                 x_by  = x_by), expDataGen)) %>%
  unnest(data) %>%
  unnest(data) %>%
  dplyr::select(B, dataset, parm_id, beta, x, y)
```

```{r expSimPlot, echo = F}
exp_data %>%
  filter(dataset == "line_data") %>%
  ggplot(aes(x = x, y = y, group = B)) +
  geom_line(alpha = 0.1) +
  facet_wrap(~beta, labeller = labeller(beta = label_both), scales = "free", ncol = 2) +
  theme_bw() +
  theme(aspect.ratio = 1)

exp_data %>%
  filter(dataset == "line_data") %>%
  ggplot(aes(x = x, y = y, group = B)) +
  geom_line(alpha = 0.1) +
  facet_wrap(~beta, labeller = labeller(beta = label_both), scales = "free", ncol = 2) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x)))
```

### Plot Aesthetics

```{r one-individual, echo = T, fig.height = 9}
point_data <- exp_data %>%
  filter(B == 1, dataset == "point_data") %>%
  select(-dataset) %>%
  nest(point_data = c("x", "y")) %>%
  expand_grid(points_end = c(10, 15)) %>%
  unnest(point_data) %>%
  mutate(y = ifelse(x <= points_end, y, NA)) %>%
  na.omit()

line_data <- exp_data %>%
  filter(B == 1, dataset == "line_data") %>%
  select(-dataset) %>%
  nest(line_data = c("x", "y")) %>%
  expand_grid(points_end = c(10, 15)) %>%
  unnest(line_data) %>%
  mutate(draw_region = factor(ifelse(x <= 10, "shown", "drawn"), levels = c("shown", "drawn")))
```

```{r one-individual-plot, echo = F, fig.height = 9}
ggplot() +
  geom_line(data = line_data, aes(x = x, y = y, linetype = draw_region), color = "steelblue", size = 1, show.legend = F) +
  geom_point(data = point_data, aes(x = x, y = y)) +
  facet_grid(beta ~ points_end, scales = "free", labeller = labeller(beta = label_both, points_end = label_both)) +
  theme_bw() +
  theme(aspect.ratio = 1)

ggplot() +
  geom_line(data = line_data, aes(x = x, y = y, linetype = draw_region), color = "steelblue", size = 1, show.legend = F) +
  geom_point(data = point_data, aes(x = x, y = y)) +
  facet_grid(beta ~ points_end, scales = "free", labeller = labeller(beta = label_both, points_end = label_both)) +
  theme_bw() +
  theme(aspect.ratio = 1) +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
                labels = trans_format("log10", math_format(10^.x)))
```

## Eye Fitting Straight Lines

```{r linearDataGen-function}
linearDataGen <-
  function(y_xbar,
           slope,
           sigma,
           N = 30,
           x_min = 0,
           x_max = 20,
           x_by  = 0.25){

    # Set up x values
    xVals <- seq(0, x_max, length.out = floor(N*1))
    xVals <- sample(xVals, N, replace = FALSE)
    xVals <- jitter(xVals)
    xVals <- ifelse(xVals < x_min, x_min, xVals)
    xVals <- ifelse(xVals > x_max, x_max, xVals)

    # From slope intercept form
    # y-y_xbar = m(x-xbar)
    # y = m(x-xbar) + y_xbar = mx - mxbar + y_xbar
    yintercept = y_xbar - slope*mean(xVals)

    # Generate "good" errors
    repeat{
      errorVals <- rnorm(N, 0, sigma)
      if(mean(errorVals[floor(N/3)]) < 2*sigma & mean(errorVals[floor(N/3)] > -2*sigma)){
        break
      }
    }

    # Simulate point data
    point_data <- tibble(dataset = "point_data",
                         x = xVals,
                         y = yintercept + slope*x + errorVals) %>%
      arrange(x)

    # Obtain least squares regression coefficients
    lm.fit <- lm(y ~ x, data = point_data)
    yintercepthat <- coef(lm.fit)[1] %>% as.numeric()
    slopehat <- coef(lm.fit)[2] %>% as.numeric()

    # Simulate best fit line data
    line_data <- tibble(dataset = "line_data",
                        x = seq(x_min, x_max, x_by),
                        y = yintercepthat + slopehat*x)

    data <- list(point_data = point_data, line_data = line_data)

    return(data)
  }
```

### Parameter Details
```{r eyefitting-Parms, echo = F}
eyefitting_parameter_details <- tibble(
                                  parm_id = c("S", "F", "V", "N"),
                                  y_xbar = c(3.88, 3.9, 3.89, 4.11),
                                  slope  = c(0.66, 0.66, 1.98, -0.70),
                                  sigma  = c(1.3, 2.8, 1.5, 2.5),
                                  x_min   = c(0, 0, 4, 0),
                                  x_max   = c(20, 20, 18, 20)) %>%
                                expand_grid(x_by = 0.25)
eyefitting_parameter_details %>% knitr::kable()
```

### Simulate Data
```{r eyefitting-Sim}
eyefitting_data <- eyefitting_parameter_details %>%
  expand_grid(B = c(1:100)) %>%
  mutate(data = purrr::pmap(list(y_xbar = y_xbar,
                                 slope = slope,
                                 sigma = sigma,
                                 x_min = x_min,
                                 x_max = x_max,
                                 x_by = x_by), linearDataGen)) %>%
  unnest(data) %>%
  unnest(data) %>%
  dplyr::select(B, dataset, parm_id, x, y)
```

```{r eyefitting-SimPlot, echo = F, fig.height = 9}
eyefitting_data %>%
  filter(dataset == "line_data") %>%
  ggplot(aes(x = x, y = y, group = B)) +
  geom_line(alpha = 0.1) +
  facet_wrap(~parm_id, ncol = 2) +
  theme_bw() +
  theme(aspect.ratio = 1)
```

### One individual

```{r eyefitting-one-individual, echo = T, fig.height = 9}
point_data <- eyefitting_data %>%
  filter(B == 1, dataset == "point_data")

line_data <- eyefitting_data %>%
  filter(B == 1, dataset == "line_data")
```

```{r eyefitting-one-individual-plot, echo = F, fig.height = 9}
ggplot() +
  geom_line(data = line_data, aes(x = x, y = y), linetype = "dashed", color = "steelblue", size = 1, show.legend = F) +
  geom_point(data = point_data, aes(x = x, y = y)) +
  facet_wrap(~ parm_id, ncol = 2) +
  theme_bw() +
  theme(aspect.ratio = 1)
```

