---
title: "Estimation (Numeric Translation)"
author: "Emily Robinson"
date: "Spring 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	cache = TRUE,
	fig.align = 'center',
	fig.width = 9,
	fig.height = 6
)
library(tidyverse)
library(plotly)
library(digest)

library(RSQLite)
library(DBI)
library(here)
library(readr)

library(lme4)
library(emmeans)
library(tictoc)
```

# Data

```{r}
# user data
db_con <- dbConnect(dbDriver("SQLite"), dbname = here("perception-of-statistical-graphics/databases/00_demographics_db.db"))
users <- dbReadTable(db_con,"users")
completed_sections <- dbReadTable(db_con,"completed_sections")
dbDisconnect(db_con)

# estimation data
db_con <- dbConnect(dbDriver("SQLite"), dbname = here("perception-of-statistical-graphics/databases/03_estimation_db.db"))
# dbListTables(db_con)
estimation_feedback <- dbReadTable(db_con,"feedback")
estimation_calcfeedback <- dbReadTable(db_con,"calc_feedback")
estimation_questions <- dbReadTable(db_con,"estimation_questions") %>%
  mutate(true_value = ifelse(q_id == "QI3", as.numeric(true_value) - 3010, true_value))
estimation_scenario_text <- dbReadTable(db_con,"scenario_text_data")
estimation_simulated_data <- dbReadTable(db_con,"simulated_data")
estimation_parameters <- dbReadTable(db_con,"true_parameters")
dbDisconnect(db_con)

# combine estimation and user data
joinCols <- c("nick_name", "ip_address", "study_starttime", "prolific_id")

# feedback data
estimation_model_data <- right_join(users, estimation_feedback, by = joinCols) %>%
  left_join(estimation_questions, by = c("q_id", "creature")) %>%
  filter(recruitment != "I am the researcher") %>%
  mutate(response = ifelse(q_id == "QE2" & creature == "tribble", as.numeric(response) - 4500, response),
         true_value = ifelse(q_id == "QE2" & creature == "tribble", as.numeric(true_value) - 4500, true_value))

factorCols <- c("nick_name", "ip_address", "prolific_id", "age", "gender", "academic_study", "computer_mouse", "recruitment", "q_id", "creature", "dataset", "scale")
estimation_model_data[,factorCols] <- lapply(estimation_model_data[,factorCols], factor)

write.csv(estimation_model_data, file = here("analyses/03-estimation/data/estimation-model-data.csv"), row.names = F, na = "")
# read in estimation_model_data
# estimation_model_data     <- read.csv(here("analyses/03-estimation/data/estimation-model-data.csv"))

estimation_model_data %>%
  select(prolific_id, q_id, creature, dataset, scale, response, qtext, true_value) %>%
  head() %>%
  knitr::kable(digits = 2)
```

## Visuals

```{r visuals, include = F, fig.width = 9, fig.height = 9}

estimation_questions %>% knitr::kable()

estimation_model_data %>%
  filter(q_id != "Q0", prolific_id != 186230) %>%
  ggplot(aes(x = scale, y = as.numeric(response), color = prolific_id)) +
  geom_jitter(width = 0.2) +
  geom_hline(aes(yintercept = true_value), linetype = "dashed") +
  facet_wrap(~q_id, scales = "free") +
  theme_bw() +
  theme(aspect.ratio = 1)
```


```{r}

estimationPlots <- function(qID){
  
  label_data <- estimation_calcfeedback %>%
  filter(q_id != "Q0", prolific_id != 186230) %>%
  filter(q_id == qID) %>%
  mutate(calculation = paste(expression, "=", round(evaluated, 2), sep = "")) %>%
  group_by(nick_name, ip_address, prolific_id, study_starttime, q_id, creature, dataset, scale) %>%
  summarise(calculation = paste(calculation, collapse = '; '))

estimation_plot_data <- estimation_model_data %>%
  filter(q_id != "Q0", prolific_id != 186230) %>%
  filter(q_id == qID) %>%
  left_join(label_data, by = c("nick_name", "ip_address", "prolific_id", "study_starttime", "q_id", "creature", "dataset", "scale")) %>%
  mutate(scratchpad = ifelse(scratchpad == "Put scratch-work here...", NA, paste(";", scratchpad))) %>%
  mutate_all(~str_replace_na(., "")) %>%
  mutate(label = paste(calculation, scratchpad))

factorCols <- c("nick_name", "ip_address", "prolific_id", "age", "gender", "academic_study", "computer_mouse", "recruitment", "order", "q_id", "creature", "dataset", "scale")
estimation_plot_data[,factorCols] <- lapply(estimation_plot_data[,factorCols], factor)
numericCols <- c("response", "true_value")
estimation_plot_data[,numericCols] <- lapply(estimation_plot_data[,numericCols], as.numeric)

summary(estimation_plot_data)

estimation_plot <- estimation_plot_data %>%
  ggplot(aes(x = response, y = prolific_id, color = scale, label = label)) +
  geom_linerange(aes(xmin = true_value, xmax = response), position = position_dodge2(0.5)) +
  geom_point(position = position_dodge2(0.5)) +
  geom_vline(aes(xintercept = true_value), linetype = "dashed") +
  facet_wrap(~q_id, scales = "free") +
  theme_bw() +
  # theme(aspect.ratio = 1) +
  # ggtitle(paste(estimation_questions$qtext[estimation_questions$q_id == qID][1], "\n ", estimation_questions$qtext[estimation_questions$q_id == qID][2])) +
  scale_color_manual(values = c("steelblue", "orange"))

return(estimation_plot)  

}

estimation_questions %>% filter(q_id == "Q0") %>% knitr::kable()
estimation_model_data %>% filter(q_id == "Q0") %>% select(prolific_id, creature, scale, response) %>% knitr::kable()

estimation_questions %>% filter(q_id == "QE1") %>% knitr::kable()
estimation_plotQE1 <- estimationPlots("QE1")
ggplotly(estimation_plotQE1)

estimation_questions %>% filter(q_id == "QE2") %>% knitr::kable()
estimation_plotQE2 <- estimationPlots("QE2")
ggplotly(estimation_plotQE2)

estimation_questions %>% filter(q_id == "QI1") %>% knitr::kable()
estimation_plotQI1 <- estimationPlots("QI1")
ggplotly(estimation_plotQI1)

estimation_questions %>% filter(q_id == "QI2") %>% knitr::kable()
estimation_plotQI2 <- estimationPlots("QI2")
ggplotly(estimation_plotQI2)

estimation_questions %>% filter(q_id == "QI3") %>% knitr::kable()
estimation_plotQI3 <- estimationPlots("QI3")
ggplotly(estimation_plotQI3)
```
